# permissions for end users to view galeras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: galera-viewer-role
rules:
- apiGroups:
  - database.example.com
  resources:
  - galeras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.example.com
  resources:
  - galeras/status
  verbs:
  - get
