# permissions for end users to edit galeras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: galera-editor-role
rules:
- apiGroups:
  - database.example.com
  resources:
  - galeras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.example.com
  resources:
  - galeras/status
  verbs:
  - get
